name: MacOS C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule
      run: |
        git submodule init
        git submodule update
    - name: cmake
      run: mkdir _build && cd _build && export PKG_CONFIG_PATH=$(brew --prefix openssl)"/lib/pkgconfig" && cmake ../ -DENABLE_CXX17=OFF
    - name: build
      run: cd _build && cmake --build ./